version: "3.9"
services:
  # Mongo DB
  mongodb:
    container_name: mongodbelective
    build: 
      dockerfile: ./Dockerfile
      context: ./MongoDb
    volumes:
      - ./MongoDb/data:/data/db
    ports:
      - "27017:27017"

  # Our load balancer
  loadbalancer:
    container_name: loadbalancer
    build: 
      dockerfile: ./Dockerfile
      context: ./LoadBalancer
    volumes:
      - ./LoadBalancer:/home/elective/work
    ports:
      - "8084:3000"
    depends_on:
      - "mongodb"

  # Main application
  ordereat:
    container_name: ordereat
    build: 
      dockerfile: ./NodeJs/Dockerfile
      context: ./
      args:
        - APP_PATH=./OrderEat
    volumes:
      - ./OrderEat/src:/home/elective/work/src
      - ./OrderEat/.env:/home/elective/work/.env
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
      - "loadbalancer"
  # Cache DB    
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - '6379:6379'

  # Our first express backend application
  express1:
    container_name: express1
    build: 
      dockerfile: ./NodeJs/Dockerfile
      context: ./
      args:
        - APP_PATH=./backend-typescript
    volumes:
      - ./backend-typescript/src:/home/elective/work/src
      - ./backend-typescript/.env:/home/elective/work/.env
    ports:
      - "8081:4000"
    environment:
      - SERVER_NAME=express1
      - PORT=4000
      - LOAD_BALANCER_HOST=loadbalancer
      - LOAD_BALANCER_PORT=3000
    depends_on:
      - "mongodb"
      - "loadbalancer"
      
  # Our second express backend application
  express2:
    container_name: express2
    build: 
      dockerfile: ./NodeJs/Dockerfile
      context: ./
      args:
        - APP_PATH=./backend-typescript
    volumes:
      - ./backend-typescript/src:/home/elective/work/src
      - ./backend-typescript/.env:/home/elective/work/.env
    ports:
      - "8082:4000"
    environment:
      - SERVER_NAME=express2
      - PORT=4000
      - LOAD_BALANCER_HOST=loadbalancer
      - LOAD_BALANCER_PORT=3000
    depends_on:
      - "mongodb"
      - "loadbalancer"